version: "3.9"
services:
  web:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true   # garante hot-reload no Windows
    volumes:
      - ./:/app
      - /app/node_modules          # evita sobrescrever node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
