version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true   # garante hot-reload no Windows
      - VITE_SHOW_ADMIN_LINK=true  # mostra link admin em dev
    volumes:
      - ./:/app
      - /app/node_modules          # evita sobrescrever node_modules
    command: npm run dev -- --host 0.0.0.0 --port 8080
